# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays


In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [11]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
a[2] = 10

In [14]:
a

array([ 1,  2, 10,  4,  5,  6])

In [16]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [21]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [26]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [32]:
n[2] = [69,69,70]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [69, 69, 70]])

In [35]:
n[:,2] = [3,3,3]
n

array([[ 1, 20,  3],
       [ 4,  5,  3],
       [69, 69,  3]])

## Randomly generated arrays


In [38]:
np.random.seed(2) #te ayuda a que no sea random siempre, a todos nos dará lo mismo con la misma semilla
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [39]:
np.random.seed(2) #te ayuda a que no sea random siempre, a todos nos dará lo mismo con la misma semilla
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [40]:
np.random.seed(2) #te ayuda a que no sea random siempre, a todos nos dará lo mismo con la misma semilla
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [43]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [44]:
a + 1 #las operaciones aplican a todos los elementos del array

array([1, 2, 3, 4, 5])

In [47]:
b = (10 + (a * 2))**2
b

array([100, 144, 196, 256, 324])

In [48]:
a + b

array([100, 145, 198, 259, 328])

## Comparison operations

In [58]:
a

array([0, 1, 2, 3, 4])

array([False, False, False, False, False])

array([False, False,  True,  True,  True])

array([2, 3, 4])

## Summarizing operations

In [61]:
b.max()

np.int64(324)

In [63]:
b.std()

np.float64(79.47829892492668)

0

### Next

Linear algebra refresher