# Machine Learning Zoomcamp

## 1.8 Linear algebra refresher

Plan:

* Vector operations
* Multiplication
    * Vector-vector multiplication
    * Matrix-vector multiplication
    * Matrix-matrix multiplication
* Identity matrix
* Inverse

In [9]:
import numpy as np

## Vector operations

In [10]:
u = np.array([1,2,3,4])
u

array([1, 2, 3, 4])

In [11]:
v = np.array([5,2,3,4])
v

array([5, 2, 3, 4])

In [12]:
u.shape

(4,)

array([3, 4, 5, 8])

array([ 2,  0,  0, 12])

## Multiplication

In [17]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result
        

In [18]:
vector_vector_multiplication(u, v)

np.float64(34.0)

In [19]:
u.dot(v)

np.int64(34)

In [50]:
W = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [65]:
j = np.array([1,2,3])


In [66]:
w.shape[0] == j.shape[0]

True

In [59]:
result = np.zeros(3)
result

array([0., 0., 0.])

In [63]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    n_rows = U.shape[0]
    
    result = np.zeros(n_rows)

    for i in range(n_rows):
        for z in range (v.shape[0]):
            result[i]+= U[i,z] * v[z]        
    return result
        
    

In [67]:
matrix_vector_multiplication(W, j)

array([14., 32., 50.])

In [69]:
W.dot(j)

array([14, 32, 50])

In [74]:
Q = np.array([
    [3,2,3],
    [4,5,6],
    [7,8,9]
])

In [75]:
W.shape == Q.shape

True

In [79]:
import numpy as np

def matrix_matrix_multiplication(U, V):
    U = np.asarray(U)
    V = np.asarray(V)

    # Comprobamos compatibilidad
    assert U.shape[1] == V.shape[0]

    n_rows = U.shape[0]
    n_cols = V.shape[1]
    n_inner = U.shape[1]     # número de columnas de U = filas de V

    result = np.zeros((n_rows, n_cols))

    for i in range(n_rows):
        for j in range(n_cols):
            for k in range(n_inner):
                result[i, j] += U[i, k] * V[k, j]

    return result

    

In [80]:
matrix_matrix_multiplication(W,Q)

array([[ 32.,  36.,  42.],
       [ 74.,  81.,  96.],
       [116., 126., 150.]])

In [81]:
W.dot(Q)

array([[ 32,  36,  42],
       [ 74,  81,  96],
       [116, 126, 150]])

In [84]:
I=np.eye(3)

In [86]:
W.dot(I)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [87]:
W


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Identity matrix

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [95]:
W[0,1]= 20
W

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [96]:
W_inv = np.linalg.inv(W)
W_inv

array([[-0.02777778, -1.44444444,  0.97222222],
       [ 0.05555556, -0.11111111,  0.05555556],
       [-0.02777778,  1.22222222, -0.69444444]])

In [98]:
W_inv.dot(W)

array([[1.00000000e+00, 8.88178420e-16, 4.44089210e-16],
       [3.46944695e-17, 1.00000000e+00, 2.08166817e-17],
       [4.44089210e-16, 0.00000000e+00, 1.00000000e+00]])

### Next 

Intro to Pandas